import styles from "./reviewer-questions.module.scss";
import { QuestionStatusBadge } from "./QuestionStatusBadge";
import type { ReviewerQuestion } from "../types/reviewer-question.types";

type QuestionTableProps = {
  questions: ReviewerQuestion[];
  onView: (question: ReviewerQuestion) => void;
};

function formatDate(value: string) {
  return new Intl.DateTimeFormat("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric"
  }).format(new Date(value));
}

export function QuestionTable({ questions, onView }: QuestionTableProps) {
  return (
    <div className={styles.tableWrap}>
      <table className={styles.table}>
        <thead>
          <tr>
            <th>Question ID</th>
            <th>Grade</th>
            <th>Subject</th>
            <th>Competency</th>
            <th>Learning Outcome</th>
            <th>Difficulty</th>
            <th>Generated By</th>
            <th>Created Date</th>
            <th>Status</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {questions.map((question) => (
            <tr key={question.id}>
              <td>
                <strong>{question.questionId}</strong>
              </td>
              <td>Grade {question.grade}</td>
              <td>{question.subject}</td>
              <td>{question.competency}</td>
              <td>{question.learningOutcome}</td>
              <td>{question.difficulty}</td>
              <td>{question.generatedBy}</td>
              <td>{formatDate(question.createdAt)}</td>
              <td>
                <QuestionStatusBadge status={question.status} />
              </td>
              <td>
                <button
                  className={styles.buttonGhost}
                  type="button"
                  onClick={() => onView(question)}
                >
                  View
                </button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
